language: node_js
node_js:
   - "7"

services:
   - mongodb

cache:
   directories:
      - node_modules

before_script:
   - sleep 15

notifications:
   email: false

branches:
   only:
      - master
